# Generated by Django 3.0.10 on 2022-04-06 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_deleted')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Tax Amount')),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Shipping Amount')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Total Amount')),
                ('status', models.CharField(blank=True, choices=[('PL', 'PLACED'), ('PR', 'PROCESSING'), ('OW', 'ON_THE_WAY'), ('OD', 'OUT_FOR_DELIVERY'), ('DL', 'DELIVERED'), ('RT', 'RETURN'), ('EX', 'EXCHANGE')], default='PL', max_length=2, null=True, verbose_name='Order Status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address_orders', to='address.ShippingAddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
