# Generated by Django 3.0.10 on 2022-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PL', 'PLACED'), ('PR', 'PROCESSING'), ('OW', 'ON_THE_WAY'), ('OD', 'OUT_FOR_DELIVERY'), ('DL', 'DELIVERED'), ('RT', 'RETURN'), ('FL', 'FAILED'), ('CL', 'CANCELLED'), ('EX', 'EXCHANGE')], default='PL', max_length=2, null=True, verbose_name='Order Status'),
        ),
    ]
