export const CART_ADD_ITEM='CART_ADD_ITEM';
export const CART_MODIFY_ITEM='CART_MODIFY_ITEM';
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM';

export const CART_CLEAR_ITEMS='CART_CLEAR_ITEMS';

export const CART_SHIPPING_ADDRESS_SAVE='CART_SHIPPING_ADDRESS_SAVE';

export const CART_PAYMENT_METHOD_SAVE='CART_PAYMENT_METHOD_SAVE';