# Generated by Django 3.0.10 on 2022-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Shipping Amount'),
        ),
    ]
