# Generated by Django 3.0.10 on 2022-04-06 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20220406_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
