# Generated by Django 3.0.10 on 2022-04-06 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20220406_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellers',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_in_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Num Reviews'),
        ),
    ]
