# Generated by Django 3.0.10 on 2022-04-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='slug',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_items', to='order.Order'),
        ),
    ]
