# Generated by Django 3.0.10 on 2022-04-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220419_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_product_item', to='product.Product'),
        ),
    ]
