# Generated by Django 3.0.10 on 2022-04-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0009_auto_20220420_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_items', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_product_items', to='product.Product'),
        ),
    ]
