# Generated by Django 3.0.10 on 2022-04-06 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_deleted')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('PE', 'PENDING'), ('PR', 'PROCESSING'), ('SF', 'SUCCESSFUL'), ('FA', 'FAILED'), ('RE', 'REFUND')], default='PE', max_length=2, null=True, verbose_name='Payment Status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Amount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
